# Generated by Django 4.2.11 on 2024-11-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('hecho', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('problema', models.CharField(max_length=20)),
                ('detalle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vecinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=50)),
                ('problema', models.CharField(max_length=20)),
            ],
        ),
    ]
